
export const USER_INPUT_SIGNAL = 'User input is comming'

export const BANK_FIELD = "bank"
export const PRODUCT_FIELD = "product"
export const PAYOUT_DATE_FIELD = "payoutDate"
export const ETP_FIELD = "etpFeasibility"
export const VIOLATION_FIELD = "violationMinimalRequirement"
export const FOREIGN_SURCHARGE_FIELD = "foreignSurcharge"
export const COUNTRY_FIELD = "country"
export const SEGMENT_FIELD = "segment"
export const BUSINESS_FIELD = "business"
export const CONTRIBUTION_MARGIN_FIELD = "contributionMargin"
export const BUSINESS_CASE_FIELD = "businessCase"
export const PROPERTY_FIELD = "typeOfProperty"
export const AMOUNT_FIELD = "amount"
export const MARKET_VALUE_FIELD = "marketValue"
export const MORTGAGE_AMOUNT_FIELD = "mortgageAmount"
export const RATING_FIELD = "rating"
export const RAING_AGENCY_FIELD= "ratingAgency"
